FeralInteractive/gamemode

README.md
This adds prerequisites install guide to Fedora.
Signed-off-by: Bruno Thomsen <bruno.thomsen@gmail.com>
=> README: added Fedora build requirements.

README.md
Also redone formatting for installation instructions and fixed a spelling error.
=> added info about overclocking

README.md
The build instructions here only cater for release 1.1.
This adds in build notes for the master branch.
=> Added build notes for the git master

daemon/cpugovctl.c, daemon/daemonize.c, daemon/gamemode.c
These are a couple of bugfixes and improvements I came up with during a security review for openSUSE (see [openSUSE bug](https://bugzilla.suse.com/show_bug.cgi?id=1093979)).
=> Bugfixes and Hardening

README.md, daemon/cpugovctl.c, daemon/daemon_config.c, daemon/daemon_config.h, daemon/gamemode-sched.c, daemon/gamemode-tests.c, daemon/gamemode.c, daemon/logging.h, daemon/main.c, data/gamemoded.8, data/gamemoded.8.in, data/gamemoderun.in, data/meson.build, example/gamemode.ini
Refactor the README now that GameMode is more established - see commits for full list of changes. See [my branch's page](https://github.com/mdiluz/gamemode/tree/minor-improvements) for what the end result looks like. Sorry for the big diff!
Also removes logging an error by default about the renice value.
=> Assorted Improvements

daemon/daemon_config.c
Don't allow these settings to be set from $HOME or $CWD, as discussed in PR #101
=> Protect the [gpu] config section

daemon/daemon_config.c, daemon/external-helper.c, daemon/governors-query.c, daemon/gpu-control.c, daemon/gpuclockctl.c
I got a [review request](https://bugzilla.suse.com/show_bug.cgi?id=1129967) for an update of gamemode on openSUSE. The code used in the gpuclockctl that can be run as root via `pkexec` has a couple of issues that I want to address with these commits.
=> Gpuclockctl fixes

.travis.yml, bootstrap.sh, lib/gamemode_client.h
- Test the examples compile (ie. `gamemode_client.h` compiles)
- Comment about blocking dbus calls
- Comment about `GAMEMODE_AUTO`
- Remove now unneeded includes
=> Small client header improvements

daemon/daemon_config.c
1. Don't look for ATTRIB changes - these spawn extra unneeded events when other watches will catch actual edits
2. Move name check code out of IN_ISDIR, I mistook IN_ISDIR to mean the event was from a dir watch, but this was incorrect
Fix for #149, to be checked by bug reporter
=> inotify fix

lib/client_impl.c
=> Turn off debug logging in client impl

README.md
http://madb.mageia.org/package/show/application/0/name/gamemode
Update to 1.4 in progress for Mageia 7.
=> Mention Mageia package in README

common/common-gpu.c
=> Fix typo s/Coudn't/Couldn't/g

README.md
It works with native games, windows games (using wine), and tested with Wii games (using dolphin emulator)
PS: It doesn't work on Steam games (no break, the gamemode is just not activate)
=> Add Lutris instructions

example/gamemode.ini
=> Make system revert to previous governor instead of "powersave"

data/io.github.feralinteractive.gamemode.metainfo.xml, data/meson.build
=> provide metainfo

.travis.yml, daemon/meson.build, data/meson.build, example/main.c, example/meson.build, lib/meson.build, meson.build
Currently travis fails for various reasons, this is an attempt to fix it (I'm still not entirely sure why it fails, I can't reproduce it). I also extended it: it now loads the example config and runs the example game to actually verify that is it working.
Btw, for some reason travis doesn't appear in PRs, I don't think this is intended (?)
Edit: looks like it works now: https://travis-ci.org/github/FeralInteractive/gamemode/builds/685589040
=> extend and fix travis

data/gamemoderun.in, data/meson.build, meson_options.txt
=> Add option to change lib dir in gamemoderun

daemon/gamemode-dbus.c, daemon/meson.build, data/meson.build, meson.build, meson_options.txt
Closes #226.
Didn't test it yet.
=> Add option to use elogind

data/gamemoded.8.in, data/gamemoderun.1.in, data/meson.build, meson.build
=> man version

data/gamemode-simulate-game.1.in, data/gamemoderun.1.in, data/meson.build
Closes #244.
Can be viewed with
```sh
man -l data/gamemode-simulate-game.1.in
```
It will only be installed if the binary will be installed as well.
Also includes a tiny fix for `data/gamemoderun.1.in`.
=> man page for example game

README.md
Add a note for Nvidia hybrid graphics users, not having the opensource
nouveau driver, which can save them some time for searching the right
solution
Signed-off-by: Ahsan Hussain <ahsan_hussain@mentor.com>
=> README.md: Update note for Nvidia Optimus proprietary driver users

meson.build
=> change location for the shipped default config

data/gamemoderun
=> Allow LD_PRELOAD overrides from GAMEMODERUNEXEC commands

data/meson.build
See https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html#usrsharemanManualPages
=> Fix installation of man pages in proper man dirs

README.md
https://www.archlinux.org/packages/community/x86_64/gamemode/
=> Gamemode is now available on Arch community repo

subprojects/inih.wrap
https://wrapdb.mesonbuild.com/inih
=> Use inih r52 from wrapdb

data/gamemode.conf, data/meson.build, meson.build
Add a trivial gamemode.conf file, which creates the gamemode group.
=> data: add and install sysusers.d gamemode.conf

.gitignore, scripts/static-analyser-check.sh
Dockerfile
----------
This dockerfile was used to emulate GitHub actions.
<details><summary>Dockerfile source (click to expand)</summary>
```dockerfile
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN set -ex; \
apt-get update; \
apt-get install -y build-essential meson appstream clang clang-format clang-tools libdbus-1-dev libinih-dev libsystemd-dev git
RUN set -ex; \
yes | adduser ci-user
USER ci-user
```
</details>
Commands to reproduce
---------------------
I simulated GitHub actions with a local docker environment.
docker build -t ci .
I ran the following commands to reproduce the issue so that I could bugfix the static analyzer script.
```bash
docker run -e CI=true --rm -v "$PWD:$PWD" -w "$PWD" --init ci ./scripts/static-analyser-check.sh
docker run -e CI=true --rm -v …
```
=> Fix GitHub Actions Static Analyzer Check

README.md
[Source](https://github.com/libretro/RetroArch/pull/13339)
=> README.md: add RetroArch to other apps section

bootstrap.sh
I have fixed the issues by implementing this change before running the script
=> Change "meson builddir..." to "meson setup builddir..." - issue #384, #399

example/gamemode.ini
=> [gamemode.ini] Add renice information about the user group.

data/polkit/rules.d/gamemode.rules.in
=> [fix] polkit parse error caused by an extra )

.github/workflows/build-and-test.yml, .gitignore, README.md, data/meson.build, meson.build, meson_options.txt, subprojects/inih.wrap
Also make a pass over the Development section of the README to reflect current distros.
=> Use Ubuntu 20.04 EOL as an excuse to update some build settings
