FeralInteractive/gamemode

- daemon/dbus_messaging.c
- lib/client_impl.c
The systemd bus headers aren't setting a POSIX compliance level so we
define the catch-all to ensure the build doesn't error out, as seen with
issue #3. This is due to the reliance of `siginfo_t`, which requires a
minimum POSIX level of `199309L` when using glibc.
Signed-off-by: Ikey Doherty <ikey@solus-project.com>
> Ensure to set `_GNU_SOURCE` for POSIX compliance with signals

- bootstrap.sh
This pull request prevents users from running the script as root. This will prevent issue #12 from happening.
> Prevent running bootstrap.sh as root

- README.md
- example/archlinux/gamemode-git/PKGBUILD
as it's already required by meson.
Also use the default unit file path (/usr/lib/systemd/user/) for packaged versions. /etc/systemd/user is intended for manually installed services.
arch-meson is just a Meson wrapper with correct arch packaging prefixes set.
> doc/examples: remove 'ninja' as explicit dep

- daemon/main.c
Hi, 
while playing around with the `sd_notify`enabled version i have noticed that the daemon never shuts itself down cleanly when being stopped by systemd. So it never logged "Quitting by request..." and resets the systemd status message. 
Apparently systemd sends a SIGTERM signal first to request the daemon to shutdown and after a delay SIGKILL will be send. So by handling SIGTERM the daemon can cleanly shutdown.
> Added SIGTERM kill signal handling

- daemon/dbus_messaging.c
- daemon/gamemode.c
- daemon/main.c
- data/gamemoded.service.in
Hi, 
i thought it would be cool to have status messages in systemctl's status output wether GameMode is currently active or not. systemd provides the sd_notify tool for this. The service file only needs the NotifyAccess option set so that systemd accepts notify events from that unit.
I added the message "GameMode is ready to be activated." in color Cyan when first started. 
When activated it says "GameMode is now active." in green. When inactive it says "GameMode is currently deactivated." 
Of course messages and colors are only a suggestion and can be changed. Also maybe i missed some places where the status message needs to be updated and somebody should take a look at this. 
Thanks.
> Integrated sd_notify to get status messages in systemd

- README.md
- lib/gamemode_client.h
- lib/meson.build
Addressing the problem brought up in #61 that for packaging in Fedora (and probably others, e.g. [debian](https://www.debian.org/doc/debian-policy/#document-ch-sharedlibs)) that shipped libraries must be versioned, we do so via libtool like versioning scheme (`current.revision.age`), which for now is just `0.0.0`. The client header then uses the versioned library, i.e. `libgamemode.so.0`.
Additionally provide package config files to ease development.
> Introduce libtool like library versioning

- data/com.feralinteractive.GameMode.service.in
- data/meson.build
- meson.build
Always install the dbus service file and specify the systemd
unit file in it. This makes the service dbus-activatable and
thus we don't need to explicitly enable it (also we have one
less daemon running, if it is not needed).
I tested it by making sure it was not yet running and then did a `LD_PRELOAD=libgamemodeauto.so sleep 60`.
```
Jun 28 19:15:28 cobalt dbus-daemon[2021]: [session uid=1000 pid=2021] Activating via systemd: service name='com.feralinteractive.GameMode' unit='gamemoded.service' requested by ':1.638'...
Jun 28 19:15:28 cobalt systemd[1997]: Starting gamemoded...
Jun 28 19:15:28 cobalt /usr/bin/gamemoded[19114]: governor is set to [powersave]
Jun 28 19:15:28 cobalt dbus-daemon[2021]: [session uid=1000 pid=2021] Successfully activated service 'com.feralinteractive.GameMode' …
```
> data: make service dbus-activatable

- scripts/format-check.sh
This commit silences the standard output of wget to generate less noise
when using `format-check.sh` as a pre-commit hook.
It also doesn't redownload the file over and over again but only when
changes were detected. Previous behavior was wget creating numbered
versions by multiple downloads, thus it always used the first version
which was download. That is obviously wrong.
It errors out nicely now when the download failed.
Signed-off-by: Kai Krakow <kai@kaishome.de>
> format-check: Optimize format-check.sh

- daemon/gamemode.c
We should not leak `SCHED_ISO` into children processes. This is obviously
a no-op if launchers use the `LD_PRELOAD` method because every child would
also preload the gamemode library (except they patch the environment
before forking).
But for games supporting gamemode natively, this prevents leaking the
scheduler settings into child processes which is important because it
children may create high CPU usage which counterfeits the original idea
of this.
Apparently, this won't work for the nice value except we would intercept
the libc forking functions (which would be possible but not very
transparent and prone to compatibility problems). However, if we
implemented it, it shouldn't be part of this commit anyway.
Signed-off-by: Kai Krakow <kai@kaishome.de>
> gamemode: Don't leak SCHED_ISO into children

- daemon/daemon_config.c
Fix what was reported by valgrind:
```
==8458==
==8458== HEAP SUMMARY:
==8458==     in use at exit: 11,677 bytes in 27 blocks
==8458==   total heap usage: 768 allocs, 741 frees, 397,008 bytes allocated
==8458==
==8458== Searching for pointers to 27 not-freed blocks
==8458== Checked 206,624 bytes
==8458==
==8458== LEAK SUMMARY:
==8458==    definitely lost: 0 bytes in 0 blocks
==8458==    indirectly lost: 0 bytes in 0 blocks
==8458==      possibly lost: 0 bytes in 0 blocks
==8458==    still reachable: 11,677 bytes in 27 blocks
==8458==         suppressed: 0 bytes in 0 blocks
==8458== Reachable blocks (those to which a pointer was found) are not shown.
==8458== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==8458==
==8458== Use --track-origins=yes to see where …
```
> Fix access to uninitialized values (valgrind)

- daemon/dbus_messaging.c
- daemon/gamemode.c
This PR adds a series of commits to detect the original game exe name from the PID if GameMode is used to run wine programs. Without this, we are not able to blacklist specific games or executables because every wine PID identifies as `wine-preloader` or `wine64-preloader`.
Please review and share your ideas. ~~I still have some fixes and todos to work on. But if you think this isn't worth inclusion or should go another route, it's good to have feedback early.~~
> Identify original wine exe by PID

- daemon/gamemode.c
During finding the cause of an issue, we discovered bad interactions
with other resource management daemon that may be running at the same
time and may interfere with GameMode's ability to properly set
scheduling parameters of the process. Usually, this results in EPERM
(instead of EINVAL for lacking kernel support). It also means that the
other daemon is leaking wrong scheduling settings into the games with
negative performance impacts (quite the opposite of what the user wanted
to achieve). So we should give some valuable hints.
This commit improves logging by detecting the error situation and giving
context-based hints on what to do next. To keep logging verbosity low,
the hint is only logged once per error code.
Closes: https://github.com/FeralInteractive/gamemode/issues/68 …
> gamemode-scheduler: Improve logging

- daemon/gamemode-env.c
- daemon/gamemode-ioprio.c
- daemon/gamemode-proc.c
- daemon/gamemode-sched.c
- daemon/gamemode-wine.c
- daemon/gamemode.c
- daemon/gamemode.h
- daemon/helpers.h
- daemon/logging.h
- daemon/meson.build
- scripts/format-check.sh
The previous PRs have shown that the code base grows too big to keep everything in one file. Thus, let's refactor it and break out functionality into separate C files. This returns `gamemode.c` almost back into its original appearance. It should result in fewer rebase and merge conflicts in the future.
This also cleans up the logging code a bit by adding some macros for easy hinting.
> Tidy up the code and refactor into modules

- bootstrap.sh
This PR makes the prefix path in `bootstrap.sh` configurable by setting a temporary variable during invocation.
$ prefix=/alternate/path ./bootstrap.sh
In a separate commit, the default is also changed to `/usr/local` as it is customary to install external software under `/usr/local`.  If the change of default is not acceptable, please feel free to revert it (or let me know, and I'll revert).
> Configurable prefix path

- daemon/gamemode-tests.c
- daemon/gamemode.h
- daemon/main.c
- daemon/meson.build
This adds the `-t` argument to `gamemoded` whereby it will perform some tests on the currently installed (and ideally running) daemon.
For now this simply verifies a few key things:
- The daemon responds correctly when we request to start and end
- The daemon correctly responds when two clients are connected
- The `-r` argument correctly requests gamemode and waits for SIGINT before cleaning it up correctly as well.
This does not test any of the gamemode functionality actually correctly applies itself to the system. Yet.
Other than verifying other PRs don't break core functionality, this should be useful for prelim support when making sure the main gamemode daemon is installed and responding correctly, we can ask "What's the output of `gamemoded -t`?".
> Add integration tests

- daemon/dbus_messaging.c
- daemon/dbus_messaging.h
- daemon/gamemode.c
Currently just requests on the `org.freedesktop.ScreenSaver` bus, took a while to get the details exactly right but appears to work.
FWIW SDL does a [little more](https://github.com/SDL-mirror/SDL/blob/master/src/video/x11/SDL_x11events.c#L1464) - it implements a tickle as well as trying to use X11 directly. GameMode could do the same but this might well do for now.
Note: an `Inhibit` call will also be cleaned up once the calling process dies (in this case, the daemon), so we're safe in the case of a crash or bailout.
Should provide the functionality that @NRG-R9T wanted in #94.
> Add code to disable the screensaver during Game Mode

- .travis.yml
- bootstrap.sh
- daemon/gamemode-sched.c
- daemon/gamemode.c
Travis now has `Xenial`! 🎉 
Use this to install the dependencies needed to run `bootstrap.sh` to verify that the full compile, install, and script itself work.
It doesn't look like a travis docker has dbus activated however, so we can't run `-t` yet, will need to consider options for that.
> Have the full bootstrap script run in the CI

- daemon/daemon_config.c
- daemon/daemon_config.h
- daemon/gamemode-gpu.c
- daemon/gamemode-ioprio.c
- daemon/gamemode-sched.c
- daemon/gamemode.c
This refactors the config get functions a little, and simplifies zeroing out config values to prevent any future accidental mistakes.
`gamemode -t` run locally to test this out, things appear to still all work correctly.
> Small config refactor

- daemon/external-helper.c
- daemon/external-helper.h
- daemon/gamemode-gpu.c
- daemon/gamemode-tests.c
- daemon/gamemode.h
- daemon/gpuclockctl.c
- daemon/main.c
This PR adds tests for the following tests and features:
Internal:
- `game_mode_get_gpu` to get the current GPU settings (to be used more later)
- `run_external_process_get_output` to get output for an external process
- `gpuclockctl` can now get the state on nvidia (amd pending)
- `gpuclockctl` now warns about a missing `DISPLAY` variable, to help diagnosis
Testing implemented for:
- `gamemoderun`
- reaper thread (same test as above)
- cpu governor setting
- custom script verification (just checks they can run)
- gpu optimization (only NV for now, AMD work still pending)
Still missing: renice, ioprio and sched tests, but due to current behavior, these are a little more complicated.
Example testing output:
```
$ gamemoded -t
: Loading config
Loading config file [/etc/gamemode.ini]
Loading …
```
> Add more test coverage

- README.md
- daemon/daemon_config.c
- daemon/daemon_config.h
- daemon/dbus_messaging.c
- daemon/gamemode-tests.c
- daemon/gamemode.c
- daemon/gamemode.h
- example/gamemode.ini
- lib/client_impl.c
- lib/gamemode_client.h
This adds support for a "supervisor" type process to request gamemode for other processes.
**External**
- `gamemode_request_start_for` to request gamemode starts for another process
- `gamemode_request_end_for` to request gamemode ends for another process
- Bugfix: when non-required functions (like the above) don't exist, we now safely fail, instead of outright bailing, see 852f096
These two client functions are a simple noop when an older daemon lib is installed.
**Config**
- `supervisor` config section for the below settings
- `require_supervisor` can be used to restrict all gamemode registrations to just supervisor functions
- `supervisor_whitelist` to whitelist specific supervisor programs (if this exists, anything not matching is rejected)
- `supervisor_blacklist` to blacklist …
> Add "supervisor" support

- daemon/daemon_config.c
- daemon/daemon_config.h
- daemon/gamemode-gpu.c
- daemon/gamemode-tests.c
- example/gamemode.ini
Remove the `gpu_vendor` config variable, this can be auto-detected from the device info in the sysfs.
Also, refactor the testing a little to reflect this and use the `GameModeGPUInfo`  type perhaps more correctly.
> Detect the GPU vendor automatically

- daemon/daemon_config.c
- daemon/daemon_config.h
- daemon/external-helper.c
- daemon/external-helper.h
- daemon/gamemode-gpu.c
- daemon/gamemode-tests.c
- daemon/gamemode.c
- daemon/gpuclockctl.c
- lib/client_impl.c
I've had these sitting for a bit. Fixes include:
* Implement timeout for external script commands, controlled by `script_timeout`
* Add output for failed external commands
* Run custom scripts last always so the internal optimizations are always applied and removed timely
* Tests now wait for a bit before running, in case a process still has gamemode and will be reaped
* Log the actual dbus errors in the client to help debugging
* Make the governor test actually check the old governor first
> Assorted small bug fixes

- daemon/daemon_config.c
- daemon/daemon_config.h
- daemon/gamemode-gpu.c
- daemon/gamemode-tests.c
- daemon/gpu-control.c
- daemon/gpu-control.h
- daemon/gpuclockctl.c
- daemon/meson.build
- example/gamemode.ini
Expanding on #111 which will now be closed.
This adds more explanation about the nv config options, while also removing the need to specify the `nv_perf_level` attribute, as it was rightly seen to be a little confusing.
This also fixes some instances where the nv clock options weren't set.
> Clean up NV optimization config

- daemon/gpuclockctl.c
This should hopefully fix issue #113, where the user was in the common situation of having an intel and an nvidia GPU, at card0 and card1 respectively, but the nvidia gpu was [gpu:0] according to the driver.
The original usage of `NV_PCIDEVICE_ATTRIBUTE` proved entirely incorrect, as that value doesn't correlate to the drm device (sorry!).
This at least works for the default cause of single-nv GPU, as well as the case in the issue of intel-nv dual gpu. It also doesn't risk an infinite loop.
I don't have a dual NV gpu system to test on however, but without being able to find an exact answer anywhere on how the gpu number is achieved, this is probably the best guess and at least works for more cases than any code we had before did!
> Try and make an educated guess at the correct nvidia gpu index

- bootstrap.sh
Note that `meson` builds [without optimizations by default](https://mesonbuild.com/Running-Meson.html#configuring-the-build-directory).
This turns `-g` into -> `-g -O2`(still keeps debug info, in case of a crash).
> Build with optimizations

- daemon/gamemode-tests.c
Instead of initializing the char array to 0 and writing N-1 bytes,
write N-1 bytes and set the last byte manually to 0. This seems
to make gcc happy.
> Rewrite strncpy to silence compiler warning

- data/meson.build
Honor prefix for installing gamemoderun to properly work in cross
environment so it can be installed in e.g. /usr/x86_64-pc-linux-gnu/bin
instead of /usr/bin like it's already done for gamemoded.
> Use path_bindir for installing gamemoderun

- daemon/dbus_messaging.c
- daemon/dbus_messaging.h
- daemon/gamemode.c
- daemon/gamemode.h
I want to write a simple GNOME shell extension that displays an icon if gamemode is active (maybe in the future a list of games requestion game mode as a menu would be nice too). For this a property that can be watched would be neat.
> Introduce a ClientCount dbus Property

- README.md
OpenSUSE packages are available at https://software.opensuse.org/package/gamemode, so let's reflect this in the README.
> Add reference to openSUSE packages

- lib/client_impl.c
On each `gamemode_request` call a new connection to d-bus is opened but the reference was never release thus leaking the connection and associated memory.
> lib: release acquired bus reference

- daemon/gamemode.c
- daemon/helpers.c
- daemon/helpers.h
- daemon/meson.build
Currently to find the executable for a game, a call to realpath(3) of /proc/<pid>/exe is made. The realpath(3) call will fail if the target does not exist (internally realpath will stat all the components of the link target path). This is a problem in the case of sandbox applications where the exe points to the absolute path *inside* the sandbox, e.g. to /app/bin/<name> in the case of flatpak. For these cases realpath(3) will then fail. Therefore use readlink(3) instead.
I have omitted the call to stat for the target because I am not sure it is necessary (and most likely the target will exist, because it just requested gamemode). I can add it though. Also by using readlink(3) we lose the ability to resolve names with `..` components but for our use case that should not matter.
> Use readlink instead of realpath so find_exe works for flatpaks

- daemon/daemon_config.c
- daemon/daemon_config.h
- daemon/gamemode-ioprio.c
- daemon/gamemode-sched.c
- daemon/gamemode-tests.c
- daemon/gamemode.c
- daemon/gamemode.h
- daemon/helpers.h
- daemon/main.c
- data/gamemoded.8.in
- lib/gamemode_client.h
This PR has the following changes:
- ioprio and niceness fixes for issue #141 and #140
- support for long command line options, and requesting with `--request=PID` for a specific process
Help now looks like:
```
Usage: gamemoded [-d] [-l] [-r] [-t] [-h] [-v]
-r[PID], --request=[PID] Toggle gamemode for process
When no PID given, requests gamemode and pauses
-s[PID], --status=[PID]  Query the status of gamemode for process
When no PID given, queries the status globally
-d, --daemonize          Daemonize self after launch
-l, --log-to-syslog      Log to syslog
-r, --test               Run tests
-h, --help               Print this help
-v, --version            Print version
See man page for more information.
```
I've also implemented tests for the two fixes above, both a302168 and a6e238d …
> ioprio and niceness fixes, and long cmdline options

- lib/client_impl.c
Add support to transparently use the portal when running inside a flatpak. This is necessary because flatpak uses pid namespace isolation (see #73) and therefore process ids need to be translated for the gamemode daemon .
This is a draft PR because it depends on flatpak/xdg-desktop-portal#314
> Add support for flatpak portal

- .travis.yml
- daemon/gamemode-gpu.c
- daemon/gamemode.c
- scripts/static-analyser-check.sh
This uses the clang static analyzer (tool name is `scan-build`) to spot issues that we may have in CI. I've also fixed up the couple it spotted.
Note: the `artifacts` entry isn't active[ without an AWS hosting instance](https://docs.travis-ci.com/user/uploading-artifacts/) annoyingly, but I've put it there for future proofing as it'd be nice to collect the full log file from scan-build if needed.
Locally, the user generally needs the `clang-tools` package installed to run the script.
The failure at 23415ac for example looks like this:
```
...
[11/31] Linking static target daemon/libdaemon-common.a.
[12/31] Compiling C object 'daemon/f77b12a@@gamemoded@exe/gamemode.c.o'.
[13/31] Compiling C object 'daemon/f77b12a@@gamemoded@exe/gamemode-env.c.o'.
../../../daemon/gamemode.c:385:7: warning: …
```
> Add a clang static analyser check and fix issues

- daemon/daemon_config.c
- daemon/daemon_config.h
- daemon/dbus_messaging.c
- daemon/gamemode.c
- daemon/gamemode.h
- example/gamemode.ini
This PR sets up two new ways to refresh the current configuration. For safety, if GameMode is active it tears down the current optimizations on both system and clients, swaps out to a new config, and then rebuilds the optimizations.
The changes provide two ways to do this:
- By watching the config locations with `inotify` for file changes, new config files, or moved and deleted config files. Currently uses the reaper thread to check the inotify file descriptor for updates.
- By using the new `RefreshConfig` dbus interface (not exposed in `gamemode_client.h` for now).
The dbus interface is implemented as a fallback, although perhaps an argument could be made that "supervisor" clients should be allowed to call this if ever needed, and a command line argument to `gamemoded` could be …
> Add config hot-reloading

- lib/client_impl.c
- lib/meson.build
- meson.build
In flatpaks systemd is not available, and thus would need to be build as an extra dependency (see [com.valvesoftware.Steam#180](https://github.com/flathub/com.valvesoftware.Steam/pull/180/files)). For the [GameMode Tester](https://github.com/gicmo/gamemode-tester) App, I re-implemented the client bits and extracted those into a separate project: [gamemode-libdbus](https://github.com/gicmo/gamemode-libdbus). The code from this PR is basically taking from there and adds support for using `libdbus`.
I am a bit unsure what is the best way to go:
- Add `libdbus` support to GameMode (this PR):
- pro: central place where code is located
- con: having  `#ifdef`/`if ! systemd_dep.found()` sprinkled all over the place and two basically different client libs in one code-base
- Use …
> Ability to use libdbus for client's dbus messaging

- meson.build
- meson_options.txt
When you need both 32 and 64 bit version of the library only one version of the utils is required. I've created an option to disable building the util folder. 
This option is with-util and is by default set to true, so it won't break any normal builds.
> added option to disable building the utils

- daemon/gamemode-context.c
- daemon/gamemode-dbus.c
- daemon/gamemode.h
For the Shell extension (or a little separate tool) as well as future integration with [GNOME Usage](https://gitlab.gnome.org/GNOME/gnome-usage) I wanted to get the list of currently registered games from gamemoded. For this I added to the `com.feralinteractive.GameMode` interface:
```
methods:
ListGames: Array of Tuples (ProcessId, ObjectPath)
signals:
GameRegistered: ProcessId, ObjectPath
GameUnregistered: ProcessId, ObjectPath
```
As well as a new `com.feralinteractive.GameMode.Game` interface:
```
properties:
ProcessId: int
Executable: string
```
This should make it possible for a client to track all currently registered games (start listening to the signals, list the current active ones and track changes via the signals). 
In order to expose the individual games, I opted for expose …
> Expose registered games on the bus

- daemon/gamemode-dbus.c
Currently, in method_list_games (`ListGames` on the bus), when `sd_bus_message_append` fails, we break the loop but then we were not reporting the error (contained in `r`) back to call.
> daemon: properly report error in error case

- README.md
- data/gamemoded.8.in
- data/gamemoderun.in
I added hybrid GPU support by adding ```$GAMEMODERUNEXEC``` to the gamemoderun launch command. If ```GAMEMODERUNEXEC``` is unset, which given by its very specific name always should be the case by default, the program will execute normal. However if you set the environment variable to a specific command like ```optirun```, it will start optirun, which starts the game.
Since the script injects libgamemodeauto globally inside the script, it will inject GameMode to the wrapper as well as the game. If a wrapper is not important for the performance (like ```env XY=Z```), the user can blacklist it.
closes #20 closes #87 
Signed-off-by: Stephan Lachnit <stephanlachnit@protonmail.com>
> Add hybrid GPU support

- common/common-helpers.c
- common/common-helpers.h
- common/common-pidfds.c
- common/common-pidfds.h
- common/meson.build
- daemon/gamemode-dbus.c
- daemon/meson.build
- lib/client_impl.c
- lib/meson.build
- meson.build
- util/meson.build
Pidfds are process file descriptors representing processes. Since Linux [5.2](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit?id=b3e5838252665ee4cfa76b82bdf1198dca81e5be) the corresponding pid in the callers pid namespace can be obtained via the fdinfo in procfs; this by reading the "Pid:" field in '/proc/self/fdinfo/<pidfd>'. In Linux 5.3 the [`pidfd_open`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit?id=32fcb426ec001cb6d5a4a195091a8486ea77e2df) system call was added, allowing us to easily open a pidfd for a given pid. Additionally select/poll/epoll can be used to monitor the status of the process, which can be used to watch for process termination.
Add a new set of APIs, analogous to the existing *byPID APIs, that work with pidfds …
> Introduce a new pidfd based set of D-Bus APIs

- bootstrap.sh
- common/common-power.c
- common/common-power.h
- common/meson.build
- daemon/gamemode-config.c
- daemon/gamemode-config.h
- daemon/gamemode-context.c
- example/gamemode.ini
This PR adds two new configuration options: igpu_desiredgov and igpu_power_threshold which allow for a different CPU governor when the Intel integrated GPU is under load.  This currently only applies to Intel integrated GPUs and not AMD APUs because it uses the Intel RAPL infrastructure for getting power information.  If on a platform that without an Intel integrated GPU or where the kernel does not support RAPL, the new options will be ignored and it will fall back to the old behavior.
One of the core principals of gamemode to date has been that, when playing a game, we want to use the "performance" CPU governor to increase CPU performance and prevent CPU-limiting.  However, when the integrated GPU is under load, this can be counter-productive because the CPU and GPU share a thermal and …
> Add an option for using a different governor for integrated GPUs

- daemon/gamemode-config.c
- meson.build
With https://github.com/benhoyt/inih/pull/97 merged, it will be easy to install inih as a system library and declare the dependency with pkg-config. gamemode should use the system library instead of including the source, but we can still use it as a fallback ([see meson reference](https://mesonbuild.com/Subprojects.html#toggling-between-system-libraries-and-embedded-sources)).
Closes #195.
> prefer system installation of inih

- data/gamemoded.service.in
Let the preferred/configured logging system to be used instead
> Don't default to syslog logging

- .gitmodules
- README.md
- meson.build
- scripts/mkrelease.sh
I added meson support to inih, so we can use upstream inih.
Only drawback is that gamemode will now install `libinih.so.47` if it is in fallback mode (i.e. linking to the shared library and not against the static), but thanks to the meson build file in upstream inih it shouldn't be hard to pack inih for distro maintainers.
It's probably a good idea to update the submodule to inih r48 once it is released and leave it there (should be fallback only anyway).
> use upstream inih r48

- .gitmodules
- scripts/mkrelease.sh
- subprojects/inih.wrap
I noticed that it's easier to use wrap (native meson dependency tool) than git submodules, since:
1. It doesn't require a git repository to work, source tree is enough.
2. It's less hassle to change or update.
3. It is a detached git head, so less annoying in git viewers.
4. Would have prevented #202.
5. Maybe more meson compatibility (#204).
> Use wrap instead of git submodule

- example/meson.build
Naming the executable `example` isn't very descriptive - so I would rename it. We actually already did this in the Debian package for a long time since we ship the executable (it's a nice thing to test weather the setup works).
> rename `example` to `gamemode-simulate-game`

- README.md
ATLauncher has supported GameMode since version 3.3.2.0 so adding it to
the list of 'games' that support gamemode without any further
configuration.
https://github.com/ATLauncher/ATLauncher/releases/tag/3.3.2.0
Please note that the change with positioning for Total War Saga is because I sorted the list alphabetically in Vim. If you would rather this not be alphabetical I am happy to change it.
> Add ATLauncher to gamemode support list and sort games alphabetically

- daemon/gamemode-context.c
- daemon/gamemode-tests.c
`i` may be out of bounds if checking are used as second part of condition.
> Check index before using array element

- example/main.c
Makes it easier to use for testing / CI.
In Debian we now use this (together with #212) to verify that our packages work after the installation, this should reduce the amount of bug reports.
> Add return values to example

- data/gamemoded.8.in
- data/gamemoderun.1
- data/meson.build
Every binary should have a man page describing what the program does, whether there are options or not - in Debian, a missing man page is even considered a bug.
Since the gamemoded man page already contained a lot of information about gamemoderun, I just copied it to a new one.
> give gamemoderun an own man page

- .gitignore
- .travis.yml
- README.md
- bootstrap.sh
- scripts/mkrelease.sh
- scripts/static-analyser-check.sh
See also #217. Since there doesn't seem to be a consensus to remove the gitignore, I would like to switch at least to `builddir` instead of `build` as it is recommended by Meson (https://github.com/mesonbuild/meson/commit/f3be687cbbfd1ff25c7ec4ffe8ba4adfee9a6579).
I also sneaked in a potential fix in `mkrelease.sh`, it could happen that the one creating the release tarball has an old version of inih, in this case meson doesn't re-download it when running `meson subprojects download`, to do this `meson subprojects update` needs to be run.
> Meson: use builddir instead of build

- lib/meson.build
Not that it would change anything in the real world, but it's good practice. Somewhat related if anyone wants to read up on the topic: https://wiki.debian.org/Multiarch/TheCaseForMultiarch#Proposed_general_solution, https://wiki.ubuntu.com/MultiarchSpec#Co-installable_-dev_packages
> Meson: explicitly set include path

- .gitignore
With meson gitignores are kinda useless, since the build files are de-coupled from the source code. Ignoring `build/` also is kinda sub-optimal since the meson project always uses `builddir` in their examples. Everyone can still use ignore stuff by using a local one .gitignore:
```gitignore
/.gitignore
/files/to/ignore
```
> remove gitignore

- scripts/mkrelease.sh
This is an attempt to remove the -dev commits after releases.
This does work quite nicely with distros too, since they either build unmodified from git anyway (e. g. Arch Linux), or from the source tarball, where no .git folder is given (e. g. Debian).
One thing I'm unsure is the `--dirty` option, this adds `-dirty` if there are non-committed changes in the workdir, it can be a nice reminder but also potentially break if your default build dir is not in a gitignore (see #217), so I would like to hear some opinions here.
> Generate version via git instead of using -dev

- daemon/meson.build
- example/meson.build
- lib/meson.build
This does a couple of things:
- `libgamemodeauto` is now also build statically, which I think is an important use case in game development.
- Various updates for misleading variable names.
- A small, but very drastic change, the pkg-config entry for libgamemodeauto is renamed. This might be a _breaking_ change for developers who actually used that entry (which I highly doubt exist btw). I think before it wasn't entirely clear how the pkg-config entries differ. I hope that this makes clear that linking against libgamemodeauto is indeed very different from using the gamemode pkg-config entry.
> Meson updates for the libraries

- common/common-pidfds.c
The function `pidfds_to_pids` expected `-1` if `open_fdinfo_dir` failed but the latter returned `errno` which is hard to distinguish from a valid file handle.  Correct that by making `open_fdinfo_dir` a wrapper around `open`.
> Align open_fdinfo_dir with pidfds_to_pids

- README.md
Hi! Since the release 1.6 has been out for 7 days I figure maybe it's time to update the README.md install guide? 
This PR bumps the version to 1.6 in the README steps. If you want people to start using this version of course. 👋🏼
> Update README instructions to point to release 1.6

- README.md
Libinih has been added to the [community] repository.
https://www.archlinux.org/packages/community/x86_64/libinih/
Also gamemode.
https://www.archlinux.org/packages/community/x86_64/gamemode/
> Add libinih pacman dependency

- data/io.github.feralinteractive.gamemode.metainfo.xml
Removes `type="console-application"`, because that's not really the case.
Adds content rating, and a comment for the icon.
> minor metainfo improvements

- README.md
- data/gamemodelist
- data/gamemodelist.1.in
- data/meson.build
While trying out gamemode on Ubuntu 18.04 I had trouble figuring out whether or not my games were running with gamemode enabled.  I wrote this utility which prints all processes loaded with the gamemode shared library.
I'm open to feedback and generally this should work for any distribution since it makes use of the Linux `/proc` filesystem.  [Learn more about `/proc`][1].
[1]: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/filesystems/proc.rst?h=v5.15.12
> New utility: gamemodelist

- daemon/gamemode-tests.c
This change fixes the format check in GitHub actions ran by `clang-format`.
<details><summary><b>Hidden environment setup (click to expand)</b></summary>
---
```dockerfile
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN set -ex; \
apt-get update; \
apt-get install -y build-essential meson appstream clang clang-format clang-tools libdbus-1-dev libinih-dev libsystemd-dev git
RUN set -ex; \
yes | adduser ci-user
USER ci-user
```
```bash
sudo su -g docker $USER
docker build -t ci .
```
</details>
---
```bash
docker run -e CI=true --rm -v "$PWD:$PWD" -w "$PWD" --init ci ./scripts/format-check.sh
```
> Fix GitHub Actions Format Check

- README.md
Added the terminal command 'gamemode -t' to the Readme file in the Install section to help people verify if GameMode has installed and will run correctly. 
Suggesting this edit after some discussion on /r/linux_gaming where a lot of people didn't know this command existed (it is listed in the --help section, but may be missed).
> Added instruction to Readme: Test if GameMode installed/running correctly

- README.md
The POSIX env [1] supports multiple `name=value` operands.
So I merged them into one.
[1] https://pubs.opengroup.org/onlinepubs/9699919799/utilities/env.html
> Simplify the offload command

- daemon/gamemode-context.c
This simple patch includes signal.h in daemon/gamemode-context.c to fix building gamemode on musl
libc.
This has been tested Gentoo musl and Alpine (also Gentoo glibc to
ensure no multiple defined symbols/other errors for glibc).
> ../daemon/gamemode-context.c: In function 'game_mode_context_auto_expire':
> ../daemon/gamemode-context.c:421:29: error: implicit declaration of function 'kill' [-Werror=implicit-function-declaration]
>   421 |                         if (kill(client->pid, 0) != 0) {
>       |                             ^~~~
> ../daemon/gamemode-context.c:421:29: warning: nested extern declaration of 'kill' [-Wnested-externs]
Signed-off-by: Alfred Persson Forsberg <cat@catcream.org>
> Fix build on musl libc

- data/meson.build
Fixes this warning:
```
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
```
> meson: fix warning in run_command

- lib/gamemode_client.h
@afayaz-feral this should fix the CI.
The reason it failed is in `lib/gamemode_client.h`:
I think the static analyser is incorrect here, as it doesn't understand the function binding. Let's add asserts to make let it believe we check for the case the function has NULL value. Should not affect the binary output in the real world as asserts are only added when compiled in debug mode.
/cc @mdiluz
> ci: fix static analyser with assertions

- common/common-pidfds.c
On glibc 2.36 pidfd_open was made available, but doesn't work without an include.
Should fix: #377
> Fix building when pidfd_open is available

- lib/client_impl.c
This change allows GameMode to call the portal dbus as opposed to daemon dbus when inside a Snap environment, the same as with Flatpak. This way, GameMode can be properly included in Snaps and used with a portal interface.
See also: https://github.com/flatpak/xdg-desktop-portal/pull/882
> Add Snap support for portals

- data/gamemodelist.1.in
- data/meson.build
- lib/meson.build
Defining the library with `library` rather than `both_libraries` allows the user to choose which type they want to install using `-Ddefault_library`.
Closes: https://github.com/FeralInteractive/gamemode/issues/287
> Don't force installation of static libgamemodeauto

- README.md
This also reorders the list from highest to lowest priority, which is generally more commonly used.
> Document some configuration files not allowing `[gpu]` changes

- README.md
- common/common-cpu.c
- common/common-cpu.h
- common/meson.build
- daemon/gamemode-config.c
- daemon/gamemode-config.h
- daemon/gamemode-context.c
- daemon/gamemode-cpu.c
- daemon/gamemode.h
- daemon/meson.build
- data/polkit/actions/com.feralinteractive.GameMode.policy.in
- data/polkit/rules.d/gamemode.rules.in
- example/gamemode.ini
- util/cpucorectl.c
- util/meson.build
First attempt at merging this patch set that adds cpu core pinning and parking capability. There is automatic logic that will try to detect if running on a CPU with non-uniform L3 cache (say 7900x3D or 7950x3D) or on a CPU with non-uniform frequencies (say Intel Alder Lake, Raptor Lake and so on with E-cores and P-cores).
By default the code will pin all the threads of the game on the cores with the better L3 or frequency but can also be configured to completely park the less desired cores (akin to how the xbox gamebar works in Windows on the 7900x3D and 7950x3D). Parking requires the aid of an new helper utility, cpucorectl, under polkit since that requires root privileges.
If logic fails or is inadequate then it is also possible to manually set which cores to pin to or which cores to …
> Adding CPU core pinning and parking capability

- daemon/gamemode-config.c
- daemon/gamemode-config.h
- daemon/gamemode-context.c
- data/polkit/actions/com.feralinteractive.GameMode.policy.in
- data/polkit/rules.d/gamemode.rules.in
- example/gamemode.ini
- util/meson.build
- util/procsysctl.c
With this patch the user can disable the split lock mitigation in the Linux kernel that otherwise can create quite sever performance penalities in some Windows games (e.g God of War).
Closes #425
> Allow user to disable the Linux kernel split lock mitigation

- common/common-cpu.h
Fixes the following build failure:
```
In file included from ../common/common-cpu.c:32:
../common/common-cpu.h:44:9: error: unknown type name 'cpu_set_t'
44 |         cpu_set_t *online;
|         ^~~~~~~~~
../common/common-cpu.h:45:9: error: unknown type name 'cpu_set_t'
45 |         cpu_set_t *to_keep;
|         ^~~~~~~~~
```
> Fix build with musl

- daemon/gamemode-cpu.c
Previously the condition would always evaluate to `false`. With the fix any core with >=95% of `max_freq` will be added to the set of cores to keep.
I tested this on my system with a 13600k by comparing the results of running a `make -j20` job with and without gamemode. With gamemode I saw the expected results, namely:
- only the first 12 cores showing significant usage with the rest being close to 0%.
- `taskset -ap $PID` returning `fff` for the `make` process, instead of the default `fffff`.
Fixes #451.
> Fix hybrid CPU core pinning

- lib/client_impl.c
When running an application without dbus connection I get the following crash:
```
GameMode ERROR: Could not connect to bus: Failed to connect to socket /run/firejail/mnt/dbus/user: Permission denied
dbus[5]: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 2832.
This is normally a bug in some application using the D-Bus library.
D-Bus not built with -rdynamic so unable to print a backtrace
```
I'm well aware that gamemode will not run without dbus but for the calling `real_gamemode_query_status`  function I would expect the function to just return the fact that it's not accessible( by returning -1) and not just close the app if failed.
> Fixed crash if dbus is not accesible

- data/gamemodelist
Systemd commit [bf1b9ae487b65b1cb1639b222724fab95e508cf5](https://github.com/systemd/systemd/commit/bf1b9ae487b65b1cb1639b222724fab95e508cf5) (present in Systemd v254 and later) effectively broke gamemodelist as the process map for the `systemd --user` process became unreadable. After this change gamemodelist would exit with an error like the following:
```
awk: fatal: cannot open file `/proc/2281/maps' for reading: Permission denied
```
To work around this let's add a hook to the awk statement to skip any files that can't be read.
Closes FeralInteractive/gamemode#456
> gamemodelist: Fix unreadable process maps

- daemon/gamemode-config.c
Fixes an issue where the build failed with musl and gcc 13.2
glibc provides a nonstandard basename implementation, this can be overriden and posix basename can be used by including libgen.h, however musl only has posix basename, and must always include libgen.h
In this particular case, it doesn't appear that using the posix version of basename will cause any issues, as it is simply being used to match a hardcoded config file name.
This is probably safe, since musl has been always been using posix basename without issues, but some further testing with glibc might be needed
> use posix basename to fix build on musl

- data/io.github.feralinteractive.gamemode.metainfo.xml
This fixes the "validate metainfo test" when building with appstream 1.0.2:
```
==================================== 2/2 =====================================
test:         validate metainfo file
start time:   02:26:39
duration:     0.03s
result:       exit status 3
command:      ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=54 /nix/store/820k815yafj6c7b3iqa2nl9qqs520ypc-appstream-1.0.2/bin/appstreamcli validate --no-net --pedantic /build/source/build/../data/io.github.feralinteractive.gamemode.metainfo.xml
----------------------------------- stdout -----------------------------------
I: io.github.feralinteractive.gamemode:6: summary-first-word-not-capitalized
I: …
```
> Add homepage url to metainfo

- .clang-format
- daemon/gamemode-context.c
- daemon/gamemode-dbus.c
- daemon/gamemode.h
According to the [Idle Inhibition Service specification](https://specifications.freedesktop.org/idle-inhibit-spec/latest/ch03.html), inhibition stops when the client disconnects from the bus:
> Inhibition will stop when the `UnInhibit` method is called, or the application disconnects from the D-Bus session bus (which usually happens upon exit).
> Fix idle inhibitor closing bus connection too early

- README.md
Since the old extension is no longer maintained by the original author and has stopped working in the latest releases of GNOME, I recommend including my extension in the README.
https://github.com/trsnaqe/gamemode-shell-extension
https://extensions.gnome.org/extension/7074/gamemode-shell-extension/
> README: Add new gamemode extension link

- meson.build
Hi, here's a minor one-line fix. When building from source I was puzzled why `bootstrap.sh` was showing 1.8.1 when I intended to install 1.8.2.
> fix project version in meson.build (1.8.1->1.8.2)

- daemon/gamemode-cpu.c
@wereii found a proper kernel way to check for the presence of P- and E-cores so we don't have to check the frequency differences.
Kept the frequency check in case the kernel way does not exist on the users kernel but upped the fail-safe to 10% from 5% to close #498
closes #498 
closes #501
> Use better kernel api for P/E-cores

- common/common-profile.c
- common/common-profile.h
- common/common-splitlock.c
- common/common-splitlock.h
- common/meson.build
- daemon/gamemode-config.c
- daemon/gamemode-config.h
- daemon/gamemode-context.c
- daemon/gamemode-tests.c
- data/polkit/actions/com.feralinteractive.GameMode.policy.in
- data/polkit/rules.d/gamemode.rules.in
- example/gamemode.ini
- util/meson.build
- util/platprofctl.c
- util/procsysctl.c
See commit messages for more details.
This adds support for setting the platform profile via `/sys/firmware/acpi/platform_profile`. It behaves very similarly to the governor, but with just one file.
Note that setting the platform profile may change other options (like the governor) and prevent them from being altered further. Thus, this also necessitates a small refactor where the initial values are stored before any changes.
The tests for platform profile treat it as required (set the status to `-1` if they fail). However, I'm not sure whether this should be the case, as I don't know how common this feature is yet.
My nitpicking also got the best of me, so I extracted split lock mitigation stuff into `common-splitlock.c`. For now, this really only matters for the path, but, in theory, …
> Support setting the platform profile

- README.md
Two weeks ago a change was made to remove a list of supported games. This pull request removes a reference to this list which still appeared in the README file.
> Update documentation to remove support reference

- common/common-profile.c
- common/common-profile.h
- daemon/gamemode-context.c
- daemon/gamemode-tests.c
If a system does not support setting the platform profile (i.e., does
not have the file `/sys/firmware/acpi/platform_profile`), then everything
that interacts with it is skipped to prevent errors.
Closes #524
> Prevent platform profile error on unsupported systems

- util/platprofctl.c
This fixes the problem that clang-18 finds. Clang-20 on newer distros generates some false positives in other places that I do not know how to disable.
> fix static analyzer error that is blocking CI

- daemon/gamemode-context.c
- daemon/gamemode-dbus.c
- daemon/gamemode.h
- daemon/gamemoded.c
- lib/client_impl.c
- lib/gamemode_client.h
This command allows GameMode to leave the context and then enter it again, which
re-applies all system optimizations. It is useful in cases where another
program (like TLP) may override GameMode's optimizations.
This is exposed to users by the `-R` or `--restart` flags to `gamemoded`.
> add RestartGamemode command

- data/gamemodelist
- data/gamemoderun
This PR changes `gamemodelist` and `gamemoderun` to use the POSIX shell, since those scripts don't depend on any bashism.
This is also helpful for downstream package maintainers, since `gamemode` will no longer depend on `bash`.
> data/gamemode*: switch to using posix shell
